// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkpkdabbqqoemebgfjfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtrcGtkYWJicXFvZW1lYmdmamZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTUwMDEsImV4cCI6MjA1OTk5MTAwMX0.LPxrBfWzkgxNfPDpxrooFIFcX2sCejpCUuSdkINr_NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);